name: Debug
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version Name'
        required: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Print env variables
        run: |
          echo "secret ${{ secrets.ORG_GRADLE_PROJECT_SIGNING_KEY }}"
          echo "secretId ${{}}"
          echo "secretAlt ${{ secrets.SIGNING_KEY }}"

          echo "Released✅"
