name: Debug
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version Name'
        required: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Print env variables
        run: echo "secretAlt ${{ secrets.SIGNING_KEY }}"
