# This is a basic workflow to help you get started with Actions
name: Publish

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version Name'
        required: true


jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"

        # Builds the release artifacts of the library
      - name: Release build
        run: |
          ./gradlew :loaders:assembleRelease
          ./gradlew androidSourcesJar 
          ./gradlew -s publishReleasePublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository
          
          echo ${secrets.ORG_GRADLE_PROJECT_SIGNING_KEY}
        env:
          ORG_GRADLE_PROJECT_VERSION_NAME: ${{ github.event.input.versionName }}
          ORG_GRADLE_PROJECT_OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_SIGNING_KEY_PASSPHRASE: ${{ secrets.SIGNING_KEY_PASSPHRASE }}
          ORG_GRADLE_PROJECT_SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_STAGING_PROFILE_ID: ${{ secrets.STAGING_ID }}