# This is a basic workflow to help you get started with Actions
name: Publish

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version Name'
        required: true


jobs:
  publish:
    name:  Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"

        # Builds the release artifacts of the library
      - name: Release build
        run: |
          ./gradlew :android-client:assembleRelease
          ./gradlew androidSourcesJar javadocJar
          ./gradlew -s publishReleasePublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository
        env:
          LIBRARY_VERSION: ${{ github.event.inputs.versionName }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_PASSPHRASE: ${{ secrets.SIGNING_KEY_PASSPHRASE }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
